[supervisord]
nodaemon=true

[program:apache]
command=/usr/local/bin/apache2-foreground
autostart=true
autorestart=true
stdout_logfile=/tmp/apache.log
stderr_logfile=/tmp/apache.err

[program:xalanproxy]
command=sh -c 'java XalanProxy'
autostart=true
autorestart=true
stdout_logfile=/tmp/xalanproxy.log
stderr_logfile=/tmp/xalanproxy.err
stdout_logfile_maxbytes=0
redirect_stderr=true
