# Definir la comunidad "public" con acceso a la vista "all"
rocommunity internal default -V all

# Permitir acceso desde cualquier dirección
agentAddress udp:161,udp6:161

# Definir la vista "all" que incluye todos los OIDs
view all included .1

# Definir el grupo de seguridad y asociarlo a la comunidad "public"
group internalGroup v2c internal

# Configurar el acceso para el grupo "publicGroup"
access internalGroup "" any noauth exact all none none