version: '3'
services:
  api:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      WebVulnLab-Network:
        ipv4_address: 172.18.0.41
    container_name: api_server_v2

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: apiabuse_database
    ports:
      - "5432:5432"
    networks:
      WebVulnLab-Network:
        ipv4_address: 172.18.0.42
    container_name: apiabuse_db_v2

  web:
    build:
      context: ./apiabuse
      dockerfile: Dockerfile
    ports:
      - "8022:80"
    volumes:
      - ./apiabuse/src:/app/src
    networks:
      WebVulnLab-Network:
        ipv4_address: 172.18.0.43
    container_name: apiabuse_v2

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8023:8025"
    networks:
      WebVulnLab-Network:
        ipv4_address: 172.18.0.44
    container_name: mail_v2

networks:
  WebVulnLab-Network:
    external: true