version: '3'
services:
  api:
    build:
      context: ./ldapserver
      dockerfile: Dockerfile
    ports:
      - "389:389"
    networks:
      WebVulnLab-Network:
        ipv4_address: 172.18.0.48
    container_name: ldap_server_v2

  web:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    ports:
      - "8021:80"
    volumes:
      - ./webserver/src:/var/www/html/
    networks:
      WebVulnLab-Network:
        ipv4_address: 172.18.0.47
    container_name: ldapinjection_v2

networks:
  WebVulnLab-Network:
    external: true