version: '3.8'
services:
  localstack:
    image: localstack/localstack:1.4.0
    environment:
      SERVICES: lambda
      EDGE_PORT: 4566
      LAMBDA_EXECUTOR: local
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DEBUG: 1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/tmp/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localstack:4566/_localstack/health"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    container_name: aws_server_v2
    networks:
      WebVulnLab-Network:
        ipv4_address: 172.18.0.45

  web:
    build: ./web
    depends_on:
      - localstack
    ports:
      - "8041:80"
    volumes:
      - ./web/index.php:/var/www/html/index.php
    container_name: aws_v2
    networks:
      WebVulnLab-Network:
        ipv4_address: 172.18.0.46

volumes:
  localstack_data:

networks:
  WebVulnLab-Network:
    external: true
