version: '3'
services:
  webdav:
    image: bytemark/webdav
    restart: always
    container_name: webdav_v2
    ports:
      - "8027:80"
    environment:
      AUTH_TYPE: Digest
      USERNAME: admin
      PASSWORD: tinkerbell
    volumes:
      #- /srv/dav:/var/lib/dav
      - ./src:/var/lib/dav