version: '3.9'

services:
  printing_db:
    container_name: oauth_printing_db_v2
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=printing_db
    networks:
      WebVulnLab-Network:
        ipv4_address: 172.18.0.50

  gallery_db:
    container_name: oauth_gallery_db_v2
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gallery_db
    networks:
      WebVulnLab-Network:
        ipv4_address: 172.18.0.51

  printing:
    container_name: oauth_printing_v2
    build:
      context: ./printing
      dockerfile: Dockerfile
    ports:
      - "8036:80"
    environment:
      - DATABASE_URI=postgresql://username:password@printing_db:5432/printing_db
    depends_on:
      - printing_db
    volumes:
      - ./printing:/app
    networks:
      WebVulnLab-Network:
        ipv4_address: 172.18.0.52

  gallery:
    container_name: oauth_gallery_v2
    build:
      context: ./gallery
      dockerfile: Dockerfile
    ports:
      - "8037:80"
    environment:
      - DATABASE_URI=postgresql://username:password@gallery_db:5432/gallery_db
    depends_on:
      - gallery_db
    volumes:
      - ./gallery:/app
    networks:
      WebVulnLab-Network:
        ipv4_address: 172.18.0.53

networks:
  WebVulnLab-Network:
    external: true