[supervisord]
nodaemon=true

[program:redis]
command=redis-server --protected-mode no
autostart=true
autorestart=true
stdout_logfile=/var/log/redis.log
stderr_logfile=/var/log/redis_err.log

[program:apache]
command=apache2-foreground
autostart=true
autorestart=true
stdout_logfile=/var/log/apache.log
stderr_logfile=/var/log/apache_err.log
